[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
lib_deps =
	esp32async/ESPAsyncWebServer@^3.9.4
	bblanchon/ArduinoJson@^7.4.2
	esp32async/AsyncTCP@^3.4.10
	pubsubclient3@^3.3.0

[env:esp32dev-ota]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
upload_protocol = espota
upload_flags =
	--debug
	--host_ip=${sysenv.OTA_HOST_IP}
	--host_port=${sysenv.OTA_HOST_PORT}
	--timeout=30
lib_deps =
	esp32async/ESPAsyncWebServer@^3.9.4
	bblanchon/ArduinoJson@^7.4.2
	esp32async/AsyncTCP@^3.4.10
	pubsubclient3@^3.3.0
    